[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.10.8"
ic-cdk = "0.14.0"
serde = "1.0.203"
serde_bytes = "0.11.14"
ic-stable-structures = "0.6.5"