[workspace]
members = [
    "src/proton_rust_backend",
    "feed/feed",
    "feed/root_feed",
    "user",
    "bucket/bucket",
    "bucket/root_bucket",
    "libraries/types",
    "fetch/comment_fetch",
    "fetch/like_fetch",
    "fetch/post_fetch",
    "fetch/root_fetch"
]
resolver = "2"
